project:
  type: website
  output-dir: docs

website:
  title: "PA446 Quarto"
  navbar:
    left:
      - href: index.qmd
        text: About
      - resume.qmd
      - spring2024.qmd

format:
  html:
    theme: cosmo
    mainfont: roboto
    css: styles.css
    toc: true

editor: visual

